<?php

declare(strict_types=1);

namespace Nowo\DashboardMenuBundle\Command;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use Nowo\DashboardMenuBundle\Entity\Menu;
use Nowo\DashboardMenuBundle\Entity\MenuItem;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

use function sprintf;

use const DIRECTORY_SEPARATOR;

/**
 * Generates a migration that creates the dashboard_menu and dashboard_menu_item tables
 * using the connection and table prefix from nowo_dashboard_menu configuration.
 *
 * If you use a non-default connection, run the migration with that connection:
 *   php bin/console doctrine:migrations:migrate --conn=YOUR_CONNECTION
 */
#[AsCommand(
    name: 'nowo_dashboard_menu:generate-migration',
    description: 'Generate a migration to create menu tables (uses config connection and table_prefix)',
)]
final class GenerateDashboardMenuMigrationCommand extends Command
{
    private const MIGRATION_TEMPLATE = <<<'PHP'
<?php

declare(strict_types=1);

namespace %s;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Dashboard Menu tables (menu + menu_item).
 * Generated by nowo_dashboard_menu:generate-migration.
 * Connection: %s | Table prefix: %s
 *
 * After generating this file, run migrations:
 *   php bin/console doctrine:migrations:migrate
 *
 * If you use a non-default connection, run (replace CONNECTION):
 *   php bin/console doctrine:migrations:migrate --conn=CONNECTION
 */
final class Version%s_CreateDashboardMenuTablesByConfiguration extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create dashboard_menu and dashboard_menu_item tables (prefix: %s)';
    }

    public function up(Schema $schema): void
    {
%s
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();
        $this->addSql($platform->getDropTableSQL('%s'));
        $this->addSql($platform->getDropTableSQL('%s'));
    }
}

PHP;

    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly string $connectionName,
        private readonly string $tablePrefix,
        ?string $name = null,
    ) {
        parent::__construct($name);
    }

    protected function configure(): void
    {
        $this
            ->addOption('path', 'p', InputOption::VALUE_REQUIRED, 'Directory where to write the migration file', 'migrations')
            ->addOption('namespace', null, InputOption::VALUE_REQUIRED, 'PHP namespace for the migration class', 'DoctrineMigrations')
            ->addOption('update', null, InputOption::VALUE_NONE, 'Generate an update migration (ALTER TABLE) for existing installations')
            ->addOption('dump', null, InputOption::VALUE_NONE, 'Only output the SQL without writing a file');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $metaMenu   = $this->em->getClassMetadata(Menu::class);
        $metaItem   = $this->em->getClassMetadata(MenuItem::class);
        $schemaTool = new SchemaTool($this->em);
        $createSql  = $schemaTool->getCreateSchemaSql([$metaMenu, $metaItem]);

        $menuTable = $metaMenu->getTableName();
        $itemTable = $metaItem->getTableName();

        $sql = $createSql;
        if ((bool) $input->getOption('update')) {
            $conn     = $this->em->getConnection();
            $platform = $conn->getDatabasePlatform();
            $sm       = method_exists($conn, 'createSchemaManager') ? $conn->createSchemaManager() : null;
            if ($sm !== null && $sm->tablesExist([$menuTable])) {
                $alterSql = [];
                $table    = $sm->introspectTable($menuTable);
                if (!$table->hasColumn('class_section_label')) {
                    $quoted     = $platform->quoteSingleIdentifier($menuTable);
                    $alterSql[] = sprintf('ALTER TABLE %s ADD class_section_label VARCHAR(512) DEFAULT NULL', $quoted);
                }
                // Only output ALTER statements for update mode.
                $sql = $alterSql;
            }
        }

        if ($input->getOption('dump')) {
            foreach ($sql as $statement) {
                $io->writeln($statement . ';');
            }
            $io->note('Run with the same connection as in nowo_dashboard_menu.doctrine.connection if different from default.');

            return Command::SUCCESS;
        }

        $path      = $input->getOption('path');
        $namespace = trim((string) $input->getOption('namespace'), '\\');
        $version   = date('YmdHis');
        $className = 'Version' . $version . '_CreateDashboardMenuTablesByConfiguration';

        $sqlLines = array_map(
            static fn (string $statement): string => '        $this->addSql(' . var_export($statement, true) . ');',
            $sql,
        );
        $sqlBlock = implode("\n", $sqlLines);

        $prefixDisplay = $this->tablePrefix === '' ? '(none)' : $this->tablePrefix;
        $content       = sprintf(
            self::MIGRATION_TEMPLATE,
            $namespace,
            $this->connectionName,
            $prefixDisplay,
            $version,
            $prefixDisplay,
            $sqlBlock,
            $itemTable,
            $menuTable,
        );

        $filesystem = new Filesystem();
        $targetDir  = $path;
        if (!$filesystem->isAbsolutePath($path)) {
            $targetDir = getcwd() . DIRECTORY_SEPARATOR . $path;
        }
        if (!is_dir($targetDir)) {
            $filesystem->mkdir($targetDir);
        }
        $file = $targetDir . DIRECTORY_SEPARATOR . $className . '.php';
        $filesystem->dumpFile($file, $content);

        $io->success(sprintf('Migration written to %s', $file));
        $io->text([
            'Connection: ' . $this->connectionName,
            'Table prefix: ' . $prefixDisplay,
            'Tables: ' . $menuTable . ', ' . $itemTable,
        ]);
        if ($this->connectionName !== 'default') {
            $io->note(sprintf('Run the migration with: php bin/console doctrine:migrations:migrate --conn=%s', $this->connectionName));
        }

        return Command::SUCCESS;
    }
}
