<?php

declare(strict_types=1);

namespace Nowo\DashboardMenuBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration for Dashboard Menu Bundle.
 *
 * In YAML you can define: project, locales, default_locale, api, dashboard.
 * All menu registration and CSS classes are stored in the database; YAML only
 * provides defaults and selector options (e.g. for CSS classes).
 *
 * @author Héctor Franco Aceituno <hectorfranco@nowo.tech>
 * @copyright 2026 Nowo.tech
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_dashboard_menu';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $root        = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('project')
                    ->info('Optional project identifier to differentiate menus when multiple apps share the same DB')
                    ->defaultNull()
                ->end()
                ->arrayNode('locales')
                    ->info('List of enabled locales for menu labels. When set, the request locale is used only if in this list; otherwise default_locale or the first locale is used.')
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                ->end()
                ->scalarNode('default_locale')
                    ->info('Fallback locale when the request locale is not in locales. If null, the first entry in locales is used.')
                    ->defaultNull()
                ->end()
                ->arrayNode('api')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultValue(true)
                        ->end()
                        ->scalarNode('path_prefix')
                            ->defaultValue('/api/menu')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('dashboard')
                    ->info('Admin dashboard to manage menus and items. Import routes with prefix (e.g. /admin/menus).')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultValue(false)
                        ->end()
                        ->scalarNode('path_prefix')
                            ->info('URL prefix for dashboard routes when imported (e.g. /admin/menus). Applied by the app when importing routes_dashboard.yaml.')
                            ->defaultValue('/admin/menus')
                        ->end()
                        ->arrayNode('route_name_exclude_patterns')
                            ->info('Regex patterns to exclude route names from the route selector (e.g. "^_" to hide internal routes, "^(web_profiler|_)" for profiler).')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('pagination')
                            ->info('Pagination for the menus list in the dashboard.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->info('When true, the menus list is paginated.')
                                    ->defaultValue(true)
                                ->end()
                                ->integerNode('per_page')
                                    ->info('Number of menus per page when pagination is enabled.')
                                    ->min(1)
                                    ->max(500)
                                    ->defaultValue(20)
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('modals')
                            ->info('Modal dialog size per type: normal (default), lg, or xl (Bootstrap 5).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('menu_form')
                                    ->info('New menu and edit menu modals.')
                                    ->defaultValue('normal')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('copy')
                                    ->info('Copy menu modal.')
                                    ->defaultValue('normal')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('item_form')
                                    ->info('Add/edit item modal.')
                                    ->defaultValue('lg')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('delete')
                                    ->info('Delete confirmation modals.')
                                    ->defaultValue('normal')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('css_class_options')
                            ->info('Lists of CSS classes shown as selectors in the dashboard when editing a menu. Override in app config to customize options.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('menu')
                                    ->info('CSS classes for the root <ul>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['nav flex-column', 'nav flex-row', 'dropdown-menu dropdown-menu-end', 'nav flex-wrap gap-2'])
                                ->end()
                                ->arrayNode('item')
                                    ->info('CSS classes for each <li>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['nav-item', 'dropdown-item', ''])
                                ->end()
                                ->arrayNode('link')
                                    ->info('CSS classes for each <a>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['nav-link', 'dropdown-item', 'nav-link link-secondary'])
                                ->end()
                                ->arrayNode('children')
                                    ->info('CSS classes for nested <ul>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['nav flex-column ms-2', 'nav flex-column', 'dropdown-menu'])
                                ->end()
                                ->arrayNode('current')
                                    ->info('CSS classes for the current <a>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['active', ''])
                                ->end()
                                ->arrayNode('branch_expanded')
                                    ->info('CSS classes for <li> when the current route is in its branch.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['active-branch', 'active-branch-has-children', ''])
                                ->end()
                                ->arrayNode('has_children')
                                    ->info('CSS classes for <li> when the item has children.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['dropdown', 'has-children', ''])
                                ->end()
                                ->arrayNode('expanded')
                                    ->info('CSS classes for <li> when its children block is open.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['expanded', ''])
                                ->end()
                                ->arrayNode('collapsed')
                                    ->info('CSS classes for <li> when its children block is closed.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['collapsed', ''])
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
