<?php

declare(strict_types=1);

namespace Nowo\DashboardMenuBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration for Dashboard Menu Bundle.
 *
 * In YAML you can define: project, locales, default_locale, api, dashboard.
 * All menu registration and CSS classes are stored in the database; YAML only
 * provides defaults and selector options (e.g. for CSS classes).
 *
 * @author Héctor Franco Aceituno <hectorfranco@nowo.tech>
 * @copyright 2026 Nowo.tech
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_dashboard_menu';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $root        = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('project')
                    ->info('Optional project identifier to differentiate menus when multiple apps share the same DB')
                    ->defaultNull()
                ->end()
                ->arrayNode('doctrine')
                    ->info('Doctrine DBAL connection and table prefix for menu entities.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('connection')
                            ->info('Name of the Doctrine DBAL connection to use (e.g. default, or a custom connection).')
                            ->defaultValue('default')
                        ->end()
                        ->scalarNode('table_prefix')
                            ->info('Prefix prepended to table names (dashboard_menu, dashboard_menu_item). Empty = no prefix.')
                            ->defaultValue('')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('cache')
                    ->info('Cache for the resolved menu tree (avoids N+1 and repeated DB hits). Uses filesystem when cache_pool is the default.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('ttl')
                            ->info('Time-to-live in seconds for the menu tree cache. Minimum 60.')
                            ->min(60)
                            ->defaultValue(60)
                        ->end()
                        ->scalarNode('pool')
                            ->info('Cache pool name (e.g. cache.app). Set to null or empty to disable tree cache.')
                            ->defaultValue('cache.app')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('icon_library_prefix_map')
                    ->info('Map full icon library names to short prefixes used when rendering the menu (e.g. bootstrap-icons → bi). Applied before passing the icon to ux_icon().')
                    ->useAttributeAsKey('library')
                    ->scalarPrototype()->end()
                    ->defaultValue(['bootstrap-icons' => 'bi'])
                ->end()
                ->arrayNode('locales')
                    ->info('List of enabled locales for menu labels. When set, the request locale is used only if in this list; otherwise default_locale or the first locale is used.')
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                ->end()
                ->scalarNode('default_locale')
                    ->info('Fallback locale when the request locale is not in locales. If null, the first entry in locales is used.')
                    ->defaultNull()
                ->end()
                ->arrayNode('permission_checker_choices')
                    ->info('Services shown in the dashboard "Permission checker" dropdown when creating/editing a Menu. Each must implement MenuPermissionCheckerInterface (canView(MenuItem, $context)). Tagged services (nowo_dashboard_menu.permission_checker) are included automatically; this list adds or orders them. Use a list of service IDs, or a map for custom labels: "FQCN: \'Display label\'".')
                    ->beforeNormalization()
                        ->ifArray()
                        ->then(static function (array $v): array {
                            if (isset($v['order'], $v['labels'])) {
                                return $v;
                            }
                            if (array_is_list($v)) {
                                return ['order' => $v, 'labels' => []];
                            }

                            return ['order' => array_keys($v), 'labels' => $v];
                        })
                    ->end()
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('order')
                            ->info('Ordered list of permission checker service IDs (FQCN). Labels come from the service tag unless overridden in labels.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('labels')
                            ->info('Optional map of service_id => label to override labels in the dropdown.')
                            ->useAttributeAsKey('service_id')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('api')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultValue(true)
                        ->end()
                        ->scalarNode('path_prefix')
                            ->defaultValue('/api/menu')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('dashboard')
                    ->info('Admin dashboard to manage menus and items. Import routes with prefix (e.g. /admin/menus).')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultValue(false)
                        ->end()
                        ->scalarNode('layout_template')
                            ->info('Twig template that dashboard views extend (e.g. @App/base.html.twig). Must define block "content". If not set or template does not exist, the bundle layout is used.')
                            ->defaultValue('@NowoDashboardMenuBundle/dashboard/layout.html.twig')
                        ->end()
                        ->scalarNode('path_prefix')
                            ->info('Deprecated: set the dashboard URL prefix in config/routes.yaml when importing routes_dashboard.yaml (e.g. prefix: /admin/menus).')
                            ->defaultValue('/admin/menus')
                            ->setDeprecated('nowo-tech/dashboard-menu-bundle', '2.0', 'The option "%path%" is deprecated. Configure the dashboard URL prefix in your app routing (e.g. config/routes.yaml or config/routes_nowo_dashboard_menu.yaml) when importing @NowoDashboardMenuBundle/Resources/config/routes_dashboard.yaml.')
                        ->end()
                        ->arrayNode('route_name_exclude_patterns')
                            ->info('Regex patterns to exclude route names from the route selector (e.g. "^_" to hide internal routes, "^(web_profiler|_)" for profiler).')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('pagination')
                            ->info('Pagination for the menus list in the dashboard.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->info('When true, the menus list is paginated.')
                                    ->defaultValue(true)
                                ->end()
                                ->integerNode('per_page')
                                    ->info('Number of menus per page when pagination is enabled.')
                                    ->min(1)
                                    ->max(500)
                                    ->defaultValue(20)
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('modals')
                            ->info('Modal dialog size per type: normal (default), lg, or xl (Bootstrap 5).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('menu_form')
                                    ->info('New menu and edit menu modals.')
                                    ->defaultValue('normal')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('copy')
                                    ->info('Copy menu modal.')
                                    ->defaultValue('normal')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('item_form')
                                    ->info('Add/edit item modal.')
                                    ->defaultValue('lg')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('delete')
                                    ->info('Delete confirmation modals.')
                                    ->defaultValue('normal')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->scalarNode('icon_selector_script_url')
                            ->info('Optional URL of the icon-selector Stimulus/script asset. When set, the dashboard layout sets window.dashboardMenuIconSelectorScriptUrl so the item form modal can init the icon selector. Use with nowo-tech/icon-selector-bundle and Symfony UX (Stimulus).')
                            ->defaultNull()
                        ->end()
                        ->integerNode('import_max_bytes')
                            ->info('Maximum size in bytes for JSON import file uploads. Default 2 MiB. Prevents DoS from very large uploads.')
                            ->min(1024)
                            ->defaultValue(2097152)
                        ->end()
                        ->scalarNode('required_role')
                            ->info('When set (e.g. ROLE_ADMIN), all dashboard routes require this role. Requires SecurityBundle. Leave null to rely on app access_control.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('import_export_rate_limit')
                            ->info('Optional rate limit for import and export actions: limit requests per interval per user/IP. E.g. { limit: 10, interval: 60 } = 10 per minute.')
                            ->canBeDisabled()
                            ->children()
                                ->integerNode('limit')
                                    ->min(1)
                                    ->defaultValue(10)
                                ->end()
                                ->integerNode('interval')
                                    ->info('Time window in seconds.')
                                    ->min(1)
                                    ->defaultValue(60)
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('css_class_options')
                            ->info('Lists of CSS classes shown as selectors in the dashboard when editing a menu. Override in app config to customize options.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('menu')
                                    ->info('CSS classes for the root <ul>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['nav flex-column', 'nav flex-row', 'dropdown-menu dropdown-menu-end', 'nav flex-wrap gap-2'])
                                ->end()
                                ->arrayNode('item')
                                    ->info('CSS classes for each <li>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['nav-item', 'dropdown-item', ''])
                                ->end()
                                ->arrayNode('link')
                                    ->info('CSS classes for each <a>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['nav-link', 'dropdown-item', 'nav-link link-secondary'])
                                ->end()
                                ->arrayNode('children')
                                    ->info('CSS classes for nested <ul>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['nav flex-column ms-2', 'nav flex-column', 'dropdown-menu'])
                                ->end()
                                ->arrayNode('section_label')
                                    ->info('CSS classes for the <span> label of section items (itemType "section").')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['menu-section-label', ''])
                                ->end()
                                ->arrayNode('current')
                                    ->info('CSS classes for the current <a>.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['active', ''])
                                ->end()
                                ->arrayNode('branch_expanded')
                                    ->info('CSS classes for <li> when the current route is in its branch.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['active-branch', 'active-branch-has-children', ''])
                                ->end()
                                ->arrayNode('has_children')
                                    ->info('CSS classes for <li> when the item has children.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['dropdown', 'has-children', ''])
                                ->end()
                                ->arrayNode('expanded')
                                    ->info('CSS classes for <li> when its children block is open.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['expanded', ''])
                                ->end()
                                ->arrayNode('collapsed')
                                    ->info('CSS classes for <li> when its children block is closed.')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['collapsed', ''])
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
