services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $allowedLocales: '%nowo_dashboard_menu.locales%'

    App\DataFixtures\:
        resource: '../src/DataFixtures/'

    App\Service\DemoMenuPermissionChecker:
        tags:
            - { name: nowo_dashboard_menu.permission_checker, label: 'Demo (user, path, permission key)' }
